### ISSUE TITLE
Creating a Project not working properly

### ISSUE THREAD

**Issue by Rumir** [TheHeadmaster/Horizon#3]
**Version Number**
Version 0.3.2-alpha

**Describe the bug**
After installing and trying to start the first project, the Error List is full with the message "ID of Mod '' and '' are the same (). Mod IDs must be unique"
No other function is available except creating a project or opening an existing one (which results in the same error)

**To Reproduce**
1. Start Horizon IDE
2. Click on "IDE"
3. Click on "File" > "New" > "Project..."
4. Name the project and select the Starbound folder (in my case: "E:\Games\Starbound")
5. Wait a few seconds
6. See error

**Expected behavior**
Being able to work with the IDE as expected.

**Screenshots and/or logs**
![image](https://user-images.githubusercontent.com/11316056/76800442-f7b7ce00-67d3-11ea-840c-3da2572d3334.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro
- OS-Version: 1903
- .NET Framework: 4.8

**Additional context**

**Comment by luxidoptera** [comment]
Corroborating; this means the IDE doesn't work at all.
Seems to have been abandoned though.

**Comment by TheHeadmaster** [comment]
I noticed that there were still people that were interested in this project, which, I admit, I hadn't touched in years as it was a personal pet project of mine that never really got off the ground. However, as long as the interest is there I'm willing to get back into it. Allow me some days to reinstate this project and I'll work on getting this issue fixed.

**Comment by TheHeadmaster** [comment]
Due to the nature of how I've started from scratch in the new major version, this issue is no longer germane. I've marked it as such and am closing it. Please keep an eye out on the new alpha releases if you are still interested in testing them out.

The alpha currently isn't in what you would call a working state (it never has been, the entirety of it has just been UI development so far), but I am continuing to be active with the project and fleshing things out as fast as I can. Thank you for your patience.
